# Module covered topic
Numpy - Nd Array Object.

Numpy - Data Types.

Numpy - Array Attributes.

Numpy - Array Creation Routines.

Numpy - Array From Existing.

Data Array From Numerical Ranges.

Numpy - Indexing & Slicing.

Numpy - Advanced Indexing.

Numpy - Broadcasting.

Numpy - Iterating Over Array

Numpy - Array Manipulation.

Numpy - Conditional operations with all and any

Numpy - String Functions.

Numpy - Mathematical Functions.

Numpy - Arithmetic Operations.

Numpy - Statistical Functions.

Sort, Search & Counting Functions.

Numpy - Linear Algebra


In [2]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

d = np.dot(A, B)
print(d)

[[ 58  64]
 [139 154]]


In [5]:
d1 = np.linalg.inv(d)
print(d1)

[[ 4.27777778 -1.77777778]
 [-3.86111111  1.61111111]]


In [7]:
d2 = np.linalg.matrix_transpose(d1)
print(d2)

[[ 4.27777778 -3.86111111]
 [-1.77777778  1.61111111]]


# Numpy Questions

### Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [28]:
# 1
arr = np.random.randint(1, 21, size=(5, 5))

print(arr)


[[14 10 19 10 10]
 [ 5 14  9  5  4]
 [ 4  8  2 19 10]
 [11  9 10  9  8]
 [ 4 14  7  6 20]]


In [31]:
arr[:, 2] = 1
print(arr)
arr[2, :] = 1
print(arr)

[[14 10  1 10 10]
 [ 5 14  1  5  4]
 [ 4  8  1 19 10]
 [11  9  1  9  8]
 [ 4 14  1  6 20]]
[[14 10  1 10 10]
 [ 5 14  1  5  4]
 [ 1  1  1  1  1]
 [11  9  1  9  8]
 [ 4 14  1  6 20]]


In [23]:
# 2
arr = np.random.randint(1, 17, size=(4, 4))
arr

array([[13,  9,  8, 15],
       [11,  8,  8,  1],
       [ 1,  8, 12, 10],
       [16, 11,  8, 13]])

In [26]:
np.fill_diagonal(arr,0)
print(arr)

[[ 0  9  8 15]
 [11  0  8  1]
 [ 1  8  0 10]
 [16 11  8  0]]


### Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [33]:
#1
arr = np.random.randint(1, 36, size=(6, 6))
print(arr)

[[32  2 29 18 30  5]
 [ 8 23  3 15 30 27]
 [15  3  3  1 27  9]
 [11  6 12  8 18  4]
 [22  7 14 12 20 20]
 [ 8 12 22  9 14 32]]


In [36]:
arr2 = arr[2:5,1:4]
print(arr[2:5,1:4])

[[ 3  3  1]
 [ 6 12  8]
 [ 7 14 12]]


In [37]:
# 2
arr = np.random.randint(1, 36, size=(5, 5))
print(arr)

[[35 11 33 32  8]
 [16  5 11 28 12]
 [16 26 27 35 15]
 [10  6 28 24 24]
 [ 4  2  3 30 33]]


In [44]:
print(arr[0, :])
print(arr[-1, :])
print(arr[1:4, 0])
print(arr[1:4, -1])

arr3 = np.concatenate((arr[0, :],arr[-1, :],arr[1:4, 0],arr[1:4, -1] ))
print(arr3)

[35 11 33 32  8]
[ 4  2  3 30 33]
[16 16 10]
[12 15 24]
[35 11 33 32  8  4  2  3 30 33 16 16 10 12 15 24]


### Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [47]:
# 1
arr1 = np.random.randint(1, 36, size=(3, 4))
arr2 = np.random.randint(1, 36, size=(3, 4))
print(arr1)
print(arr2)

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)


[[35 28 17 16]
 [12 24 12 10]
 [35 33 18 26]]
[[29 11 28 10]
 [ 5 34 15 31]
 [25 19 13 26]]
[[64 39 45 26]
 [17 58 27 41]
 [60 52 31 52]]
[[  6  17 -11   6]
 [  7 -10  -3 -21]
 [ 10  14   5   0]]
[[1015  308  476  160]
 [  60  816  180  310]
 [ 875  627  234  676]]
[[1.20689655 2.54545455 0.60714286 1.6       ]
 [2.4        0.70588235 0.8        0.32258065]
 [1.4        1.73684211 1.38461538 1.        ]]


In [49]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.
# 2

arr = np.random.randint(1, 5, size=(4, 4))
print(arr)

[[2 2 2 2]
 [1 3 2 2]
 [2 1 3 1]
 [4 3 3 4]]


In [52]:
row_sum = np.sum(arr, axis=1)
print("Row sum ", row_sum)
col_sum = np.sum(arr, axis=0)
print("Col sum ", col_sum)


Row sum  [ 8  8  7 14]
Col sum  [ 9  9 10  9]


### Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [56]:
arr = np.random.randint(1, 25, size=(4, 4))
print(arr)
print("Mean = ", np.mean(arr))
print("Meadian = ", np.median(arr))
print("Standard Deviatio = ", np.std(arr))
print("Variance = ", np.var(arr))
print(dir(np))

[[20 23 21 11]
 [24 22 19 23]
 [ 1 13 10  1]
 [19 14 24 16]]
Mean =  16.3125
Meadian =  19.0
Standard Deviatio =  7.260498863714531
Variance =  52.71484375
['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arct

### Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [58]:
# 1
arr = np.random.randint(1, 25, size=(3, 3))
arr1 = np.random.randint(1, 25, size=(3,))

print(arr)
print(arr1)
print(arr+arr1)

[[18 15  6]
 [17 20  9]
 [ 7 20 12]]
[16  6  9]
[[34 21 15]
 [33 26 18]
 [23 26 21]]


In [71]:
# print(arr1[:, np.newaxis])
# print(arr1[np.newaxis, :])
# print(arr1[:,np.newaxis])
print(arr1)  # 3
arr1.shape
arr2 = arr1.reshape(3, 1) # row =3, col = 1

print(arr - arr2)

[16  6  9]
[[  2  -1 -10]
 [ 11  14   3]
 [ -2  11   3]]


### Linear Algebra

1. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [72]:
# 1
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])
print(np.dot(A, B))

[[ 58  64]
 [139 154]]


### Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [75]:
# 1
arr = np.random.randint(1, 10, size=(3, 3))
print(arr)

print(arr.reshape(1, 9))
print(arr.reshape(9, 1)) # row = 9 , col = 1

[[8 6 7]
 [2 7 9]
 [5 1 6]]
[[8 6 7 2 7 9 5 1 6]]
[[8]
 [6]
 [7]
 [2]
 [7]
 [9]
 [5]
 [1]
 [6]]


In [94]:
# 2
arr = np.random.randint(1, 10, size=(5, 5))
print(arr)
flatten_arr = arr.flatten()
print(flatten_arr)
arr2 = flatten_arr.reshape(6,5)
print(arr2)

[[7 4 3 4 5]
 [7 7 9 9 5]
 [5 2 4 2 4]
 [3 5 9 8 4]
 [1 5 9 6 8]]
[7 4 3 4 5 7 7 9 9 5 5 2 4 2 4 3 5 9 8 4 1 5 9 6 8]
[[7 4 3 4 5]
 [7 7 9 9 5]
 [5 2 4 2 4]
 [3 5 9 8 4]
 [1 5 9 6 8]]


In [95]:
import numpy as np

def reshape_matrix(a: list[list[int|float]], new_shape: tuple[int, int]) -> list[list[int|float]]:
	#Write your code here and return a python list after reshaping by using numpy's tolist() method
  arr = np.array(a)
  if arr.size != new_shape[0] * new_shape[1]:
      return []
  arr = arr.reshape(new_shape[0],new_shape[1])
  return arr.tolist()

print(reshape_matrix([[1,2,3,4],[5,6,7,8]], (2, 4)))

[[1, 2, 3, 4], [5, 6, 7, 8]]


### **Boolean Indexing**

1. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [88]:
arr = np.random.randint(1, 100, size=(5, 5))
arr
print(arr)

[[98 24  6 57 45]
 [92 21 59 74 32]
 [39 45 19  7 20]
 [ 7 48 64 58 11]
 [12 72 97 86 55]]


In [91]:
print(arr[arr>10])
arr[arr>10] = 10
print(arr)

[98 24 57 45 92 21 59 74 32 39 45 19 20 48 64 58 11 12 72 97 86 55]
[[10 10  6 10 10]
 [10 10 10 10 10]
 [10 10 10  7 10]
 [ 7 10 10 10 10]
 [10 10 10 10 10]]


# Problem Solving


Easy
https://www.deep-ml.com/problems/3

In [ ]:
import numpy as np

def reshape_matrix(a: list[list[int|float]], new_shape: tuple[int, int]) -> list[list[int|float]]:
    #Write your code here and return a python list after reshaping by using numpy's tolist() method
    arr = np.array(a)
    if arr.size != new_shape[0] * new_shape[1]:
        return []
    arr = arr.reshape(new_shape[0],new_shape[1])
    return arr.tolist()

Easy
https://www.deep-ml.com/problems/5

In [ ]:
import numpy as np
def scalar_multiply(matrix: list[list[int|float]], scalar: int|float) -> list[list[int|float]]:
    arr = np.array(matrix)
    arr = arr * scalar
	return arr.tolist()

Easy
https://www.deep-ml.com/problems/35

In [ ]:
import numpy as np

def make_diagonal(x):
	# Your code here
	return np.diag(x)

Easy
https://www.deep-ml.com/problems/83


In [ ]:
import numpy as np

def calculate_dot_product(vec1, vec2) -> float:
	"""
	Calculate the dot product of two vectors.
	Args:
		vec1 (numpy.ndarray): 1D array representing the first vector.
		vec2 (numpy.ndarray): 1D array representing the second vector.
	"""
	# Your code here
	return np.dot(vec1, vec2)

Easy
https://www.deep-ml.com/problems/121