In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.0.2


In [3]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__annotations__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsor

In [5]:
# 1D
a = np.array([1, 2,3])
print(type(a))

<class 'numpy.ndarray'>


In [11]:
# 2D
b = np.array([[1,2,3], [4,5,6]])
print(type(b))

print(b.ndim, b.shape, b.size)

<class 'numpy.ndarray'>
2 (2, 3) 6


In [12]:
print(b.dtype)

int64


In [15]:
c = np.array([1,2,4.5], dtype=np.int64)
print(c.dtype)
print(c)

int64
[1 2 4]


In [23]:
print(np.zeros((3,3)))
print(np.ones((3,4)))
print(np.full((3,4), 10))
print(np.eye(7))
print(np.empty((1,2)))
print(np.random.randint(10, 20, (4,4)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
[[-5.93035306e-005  9.61751788e+193]]
[[18 13 18 11]
 [13 15 13 15]
 [15 13 14 11]
 [12 17 11 15]]


In [30]:
print(np.arange(0, 11, 5))
print(np.linspace(0, 1, 10))

[ 0  5 10]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [32]:
a = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [35]:
a[0][1]

np.int64(20)

In [36]:
a[1, 1]

np.int64(50)

In [37]:
a[0, :]

array([10, 20, 30])

In [39]:
a[0, 0:2]

array([10, 20])

In [42]:
a[:, 0]

array([10, 40, 70])

In [43]:
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [45]:
print(a[-1, :])

[70 80 90]


In [46]:
print(a[:, -1])

[30 60 90]


In [47]:
print(np.diag(a))

[10 50 90]


In [48]:
print(a[0:2, 0:2])

[[10 20]
 [40 50]]


In [52]:
a = np.array([10, 20, 30, 40, 50])

print(a[[0, 2, 4]])


[10 30 50]


In [54]:
print(a[a>40])

[50]


In [55]:
print(a[a%20==0])

[20 40]


In [61]:
a = np.array([10, 20, 30, 40, 50, 60])

print(a)
print(a.reshape(2,3))
print(a.reshape(3,2))
# print(a.reshape(3,3))

[10 20 30 40 50 60]
[[10 20 30]
 [40 50 60]]
[[10 20]
 [30 40]
 [50 60]]


ValueError: cannot reshape array of size 6 into shape (3,3)

In [63]:
print(a.reshape(3,2))
print(a.reshape(3,2).T)

[[10 20]
 [30 40]
 [50 60]]
[[10 30 50]
 [20 40 60]]


In [66]:
a = np.array([3, 7, 2, 9, 5])
print(a)

[3 7 2 9 5]


In [68]:
# all => AND
print(np.all(a>5))

False


In [70]:
# any => OR
print(np.any(a>5))
print(np.any(a>50))

True
False


In [71]:
a = np.array(['hello', 'world', 'numpy'])

In [77]:
print(np.char.upper(a))
print(np.char.capitalize(a))
print(np.char.add(a, "+"))
print(np.char.startswith(a,'n'))

print(np.char.split("one two three four"))

['HELLO' 'WORLD' 'NUMPY']
['Hello' 'World' 'Numpy']
['hello+' 'world+' 'numpy+']
[False False  True]
['one', 'two', 'three', 'four']


In [81]:
a = np.array([0, np.pi/2, np.pi])
print(a)
print(np.sin(a))
print(np.cos(a))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [86]:
b = np.array([1, 4, 9, 16])

print(np.sqrt(b))
print(np.log(b))
print(np.log10(b))
print(np.exp(a))

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[0.         0.60205999 0.95424251 1.20411998]
[ 1.          4.81047738 23.14069263]


In [123]:
a = np.array([[2, 4, 6], [1, 3, 5]])

print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.percentile(a, 50))
print(np.var(a))

3.5
3.5
1.707825127659933
3.5
2.9166666666666665


In [95]:
result = np.mod(10, 3)
print(result)

1


In [99]:
a = np.array([3, 1, 4, 1, 5, 9, 2, 6])

print(np.sort(a))
print(np.argsort(a))
print(np.argmax(a))
print(np.argmin(a))

[1 1 2 3 4 5 6 9]
[1 3 6 0 2 4 7 5]
5
1


In [105]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

d = np.dot(A, B)
print(d)

[[ 58  64]
 [139 154]]


In [104]:
print(np.linalg.inv(d))

[[ 4.27777778 -1.77777778]
 [-3.86111111  1.61111111]]


In [106]:
print(np.linalg.matrix_transpose(d))

[[ 58 139]
 [ 64 154]]


### Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0. [ Home work]

In [107]:
a = np.random.randint(1, 21, (5,5))
print(a)

[[ 6 18 11 15 17]
 [15 15 14 16 13]
 [17 10 19  2  5]
 [ 2  2 16  8  4]
 [16 18  3 12  5]]


In [109]:
print(a[:, 2])
a[:, 2] = 1
print(a)

[11 14 19 16  3]
[[ 6 18  1 15 17]
 [15 15  1 16 13]
 [17 10  1  2  5]
 [ 2  2  1  8  4]
 [16 18  1 12  5]]


### Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border. (HW)

In [111]:
a = np.random.randint(1, 36, (6,6))
print(a)

[[13  7  9 24  7 28]
 [10 26 23  5 32 23]
 [28 24 32 31 12 28]
 [34  4 23  5 34 16]
 [25 23 33  4  2 28]
 [ 3 13 32 15  4 19]]


In [112]:
print(a[2:5, 1:4])

[[24 32 31]
 [ 4 23  5]
 [23 33  4]]


In [113]:
a = np.random.randint(1, 36, (6,6))
b = np.random.randint(1, 36, (6,6))

print(a[1], b[1])

[18 21  3  9 12 21] [27 33 31 16 31 16]


In [115]:
np.concatenate((a[1], b[1]))

array([18, 21,  3,  9, 12, 21, 27, 33, 31, 16, 31, 16])

### Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [116]:
a = np.random.randint(1, 36, (3,4))
b = np.random.randint(1, 36, (3,4))

print(a +b)
print(a -b)

[[30 12 44 55]
 [32 43 20 22]
 [20 38 52 40]]
[[-16   2 -22  -9]
 [ 30  21   0  -8]
 [ 18  32  -2 -18]]


In [119]:
# 2
a = np.random.randint(1, 3, (4,4))
print(a)

[[1 1 1 1]
 [2 2 2 2]
 [2 2 1 1]
 [1 1 1 2]]


In [120]:
print(np.sum(a))

23


In [121]:
# row
print(np.sum(a, axis=1))

[4 8 6 5]


In [122]:
# col
print(np.sum(a, axis=0))

[6 6 5 6]


### Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array. ( HW)

### **Boolean Indexing**

1. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [124]:
a = np.random.randint(1, 30, (4,4))
print(a)

[[ 8 13 14  4]
 [ 7 21 16 18]
 [22  2  1 25]
 [12  6  2 19]]


In [126]:
a[a>10]= 10
print(a)

[[ 8 10 10  4]
 [ 7 10 10 10]
 [10  2  1 10]
 [10  6  2 10]]


Easy
https://www.deep-ml.com/problems/3

Easy
https://www.deep-ml.com/problems/5 ( HW )

Easy
https://www.deep-ml.com/problems/35

Easy
https://www.deep-ml.com/problems/83

Easy
https://www.deep-ml.com/problems/121